In [3]:
import numpy as np
import pandas as pd
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

# Reading Dataset

In [4]:
data=pd.read_csv('data.csv',error_bad_lines=False) #Enter your dataset
data.head()#location on your computer.


Skipping line 2810: expected 2 fields, saw 5
Skipping line 4641: expected 2 fields, saw 5
Skipping line 7171: expected 2 fields, saw 5
Skipping line 11220: expected 2 fields, saw 5
Skipping line 13809: expected 2 fields, saw 5
Skipping line 14132: expected 2 fields, saw 5
Skipping line 14293: expected 2 fields, saw 5
Skipping line 14865: expected 2 fields, saw 5
Skipping line 17419: expected 2 fields, saw 5
Skipping line 22801: expected 2 fields, saw 5
Skipping line 25001: expected 2 fields, saw 5
Skipping line 26603: expected 2 fields, saw 5
Skipping line 26742: expected 2 fields, saw 5
Skipping line 29702: expected 2 fields, saw 5
Skipping line 32767: expected 2 fields, saw 5
Skipping line 32878: expected 2 fields, saw 5
Skipping line 35643: expected 2 fields, saw 5
Skipping line 36550: expected 2 fields, saw 5
Skipping line 38732: expected 2 fields, saw 5
Skipping line 40567: expected 2 fields, saw 5
Skipping line 40576: expected 2 fields, saw 5
Skipping line 41864: expected 2 field

password  strength
0     kzde5577         1
1     kino3434         1
2    visi7k1yr         1
3     megzy123         1
4  lamborghin1         1

In [5]:
data['strength'].unique() # Here 1 refers average strength, 2 refers strong strength and 0 refers weak strength.

array([1, 2, 0])

# Code to remove all the missing(Null/NaN) values in my Dataset

In [6]:
data.isna().sum()

password    1
strength    0
dtype: int64

In [7]:
data[data['password'].isnull()]

password  strength
367579      NaN         0

In [8]:
data.dropna(inplace=True)

In [9]:
data.isnull().sum()

password    0
strength    0
dtype: int64

In [10]:
password_arr=np.array(data)

In [11]:
password_arr

array([['kzde5577', 1],
       ['kino3434', 1],
       ['visi7k1yr', 1],
       ...,
       ['184520socram', 1],
       ['marken22a', 1],
       ['fxx4pw4g', 1]], dtype=object)

# Random shuffling will give my model Robustness

In [12]:
import random
random.shuffle(password_arr)

In [13]:
x=[passwords[0] for passwords in password_arr]
y=[strength[1] for strength in password_arr]


In [14]:
x

['kzde5577',
 'kzde5577',
 'kzde5577',
 'kzde5577',
 'kzde5577',
 'AVYq1lDE4MgAZfNt',
 'kino3434',
 'v1118714',
 'universe2908',
 'AVYq1lDE4MgAZfNt',
 'megzy123',
 '612035180tok',
 'universe2908',
 'asv5o9yu',
 'u6c8vhow',
 'universe2908',
 'as326159',
 'kino3434',
 'jytifok873',
 'megzy123',
 '52558000aaa',
 '52558000aaa',
 '6975038lp',
 'jytifok873',
 'jytifok873',
 'megzy123',
 'visi7k1yr',
 'intel1',
 'cigicigi123',
 '52558000aaa',
 'AVYq1lDE4MgAZfNt',
 'schalke04',
 'asv5o9yu',
 'universe2908',
 'g067057895',
 'gaymaids1',
 'kino3434',
 'kzde5577',
 'exitos2009',
 '52558000aaa',
 'kswa2mrv',
 'visi7k1yr',
 'lamborghin1',
 'visi7k1yr',
 'universe2908',
 'megzy123',
 'AVYq1lDE4MgAZfNt',
 'yqugu927',
 '612035180tok',
 'WUt9IZzE0OQ7PkNE',
 'as326159',
 '612035180tok',
 '0169395484a',
 'alimagik1',
 'as326159',
 'universe2908',
 'alimagik1',
 '52558000aaa',
 'elyass15@ajilent-ci',
 'exitos2009',
 'lsdlsd1',
 'as326159',
 'lamborghin1',
 'olmaz.',
 'klara-tershina3H',
 'yk530mg8',
 'yqu

# Create a function to split the input into characters of list

In [15]:
def split(inputs):
    character=[]
    for i in inputs:
        character.append(i)
    return character

In [16]:
split('kzded5577')

['k', 'z', 'd', 'e', 'd', '5', '5', '7', '7']

# Importing TF-IDF Vectorizer

In [17]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [18]:
vectorizer=TfidfVectorizer(tokenizer=split)

# Applying TF-IDF vectorizer on my data

In [19]:
Matrix=vectorizer.fit_transform(x) # Transform the data: X

In [20]:
print(vectorizer.vocabulary_)# We can see that all words were made lowercase by default and that the punctuation was ignored if
                             #it is there.
                             # Returns a dictionary comprised of the tokens and their respective indices in the array.

{'k': 58, 'z': 73, 'd': 51, 'e': 52, '5': 31, '7': 33, 'a': 48, 'v': 69, 'y': 72, 'q': 64, '1': 27, 'l': 59, '4': 30, 'm': 60, 'g': 54, 'f': 53, 'n': 61, 't': 67, 'i': 56, 'o': 62, '3': 29, '8': 34, 'u': 68, 'r': 65, 's': 66, '2': 28, '9': 35, '0': 26, '6': 32, 'c': 50, 'h': 55, 'w': 70, 'j': 57, 'p': 63, 'x': 71, 'b': 49, '@': 41, '-': 23, '.': 24, '>': 39, '!': 13, '&': 18, '?': 40, '<': 37, ';': 36, '_': 46, '/': 25, ' ': 12, '^': 45, '#': 15, '+': 22, '(': 19, ')': 20, '"': 14, '~': 77, '$': 16, 'ú': 119, '*': 21, '%': 17, '{': 74, '}': 76, '±': 86, '\\': 43, '=': 38, '[': 42, ']': 44, '³': 88, 'ô': 115, '`': 47, '\x16': 5, 'ó': 114, 'ò': 113, '·': 92, '\x1e': 11, '¿': 97, '\x1c': 10, '\x05': 0, '\x1b': 9, '\x19': 8, 'þ': 123, 'ä': 103, '«': 84, '|': 75, '°': 85, '\x7f': 78, '²': 87, 'à': 100, 'õ': 116, 'ð': 111, '¾': 96, 'ß': 99, '´': 89, 'å': 104, 'ÿ': 124, 'ý': 122, '\x10': 3, '\x17': 6, '÷': 118, 'ö': 117, 'â': 102, 'û': 120, '¨': 83, 'é': 107, '\x06': 1, 'á': 101, 'º': 94, '¡'

In [21]:
Matrix.shape #We have 669639 rows (669639 passwords) and 124 columns (124 unique words).

(669639, 129)

In [22]:
vectorizer.get_feature_names_out() # Print all the features(unique words) of the vectorizer.

array(['\x05', '\x06', '\x08', '\x10', '\x12', '\x16', '\x17', '\x18',
       '\x19', '\x1b', '\x1c', '\x1e', ' ', '!', '"', '#', '$', '%', '&',
       '(', ')', '*', '+', '-', '.', '/', '0', '1', '2', '3', '4', '5',
       '6', '7', '8', '9', ';', '<', '=', '>', '?', '@', '[', '\\', ']',
       '^', '_', '`', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j',
       'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w',
       'x', 'y', 'z', '{', '|', '}', '~', '\x7f', '\x8d', '\xa0', '¡',
       '¢', '¨', '«', '°', '±', '²', '³', '´', 'µ', '¶', '·', '¹', 'º',
       '¼', '¾', '¿', '×', 'ß', 'à', 'á', 'â', 'ä', 'å', 'æ', 'ç', 'é',
       'ê', 'í', 'ï', 'ð', 'ñ', 'ò', 'ó', 'ô', 'õ', 'ö', '÷', 'ú', 'û',
       'ü', 'ý', 'þ', 'ÿ', 'œ', '—', '‹', '›'], dtype=object)

In [23]:
FirstDocVector=Matrix[0]
FirstDocVector

<1x129 sparse matrix of type '<class 'numpy.float64'>'
	with 6 stored elements in Compressed Sparse Row format>

In [24]:
FirstDocVector.T.todense() # Print the sparse matrix of the test data.

matrix([[0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.56760596],
        [0.        ],
        [0.59138838],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0

In [25]:
df=pd.DataFrame(FirstDocVector.T.todense(),index=vectorizer.get_feature_names_out(),columns=['TF-IDF'])
df.sort_values(by=['TF-IDF'],ascending=False)

TF-IDF
7   0.591388
5   0.567606
z   0.335665
k   0.291612
d   0.285510
..       ...
=   0.000000
<   0.000000
;   0.000000
9   0.000000
›   0.000000

[129 rows x 1 columns]

# Split the data into Training set and Test set
Training set-> A subset to train my model

Test set-> A subset to test my trained model

In [26]:
from sklearn.model_selection import train_test_split

In [27]:
Matrix_train, Matrix_test, y_train, y_test=train_test_split(Matrix,y,test_size=0.3)
#X->independent data, x->dependent data
#0.3->30% of my data is considered for the testing purpose. Therefore the rest 70% of my data will be condidered for the
#training purpose.

In [28]:
Matrix_train.shape

(468747, 129)

# Applying Logistic Regression as we are doing Classification of Passwords

In [29]:
from sklearn.linear_model import LogisticRegression

In [30]:
clf=LogisticRegression(random_state=0,multi_class='multinomial')

In [31]:
clf.fit(Matrix_train,y_train)

LogisticRegression(multi_class='multinomial', random_state=0)

## Performing predictions on the strength of passwords which are outside of my data

In [32]:
dt=np.array(['Iron@#$Man123'])
prediction=vectorizer.transform(dt)
clf.predict(prediction)

array([2])

# Performing prediction on Matrix-Test data

In [33]:
y_prediction=clf.predict(Matrix_test)
y_prediction

array([1, 1, 0, ..., 1, 1, 2])

### Checking accuracy of my model using confusion_matrix,accuracy_score

In [34]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [35]:
cm=confusion_matrix(y_test,y_prediction)
print(cm)
print(accuracy_score(y_test,y_prediction))

[[  7915  18964     27]
 [  5778 139610   3703]
 [    45   7736  17114]]
0.8195398522589252


# Report of my model

In [36]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_prediction))

              precision    recall  f1-score   support

           0       0.58      0.29      0.39     26906
           1       0.84      0.94      0.89    149091
           2       0.82      0.69      0.75     24895

    accuracy                           0.82    200892
   macro avg       0.75      0.64      0.67    200892
weighted avg       0.80      0.82      0.80    200892

